# Site settings

 url      :  "http://www.keithbuhler.com/academic"
 baseurl  :  "/academic"
 locale:         "en"
 title:          "<b>keithbuhler.com</b>"
 pitch:  "Pursuing virtue and wisdom"
 description:    "Thoughts, projects, and blog of Dr. Keith Buhler, philosopher, classical educator, and writer."


# Social

facebook:
  username  : "keithedbuhler" 
github      : 
  username  : "keithbuhler"

# author info
author:
  name      : "Keith Buhler"
  avatar    : "avatar.png"
  bio       : "Philosopher, classical educator, and author"
  email     : "keithedbuhler@gmail.com"
  url       : "https://www.keithbuhler.com"
  google_plus:  "+KeithBuhler"
  facebook  : "keithedbuhler" 
  twitter   : "Keith_Buhler"
  youtube   : "https://www.youtube.com/channel/UCDxfeT2v6-kFM12T7zD-K9Q"
  curriculum: 
    name: CV
    url: http://www.keithbuhler.com/cv



social: 
  type: 
  name: 
  links:
    - "https://twitter.com/Keith_Buhler"
    - "https://facebook.com/keithedbuhler"
    - "https://www.linkedin.com/in/yourprofile"
    - "https://plus.google.com/+Keith_Buhler"

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-71712734-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

analytics:
  provider: "google-universal"
    tracking_id: "UA-71712734-1"


timezone:    America/New_York
future:      true
highlighter: rouge

# Gems

gems: 
  - [jekyll-paginate]
  - [jekyll-sitemap]
  - [jekyll-feed]
  - [jekyll-gist]
  - [jekyll-archives]
sass:
  sass_dir: _sass
  style: compressed


nb_posts_page: 3
archive_permalink:
repo: http://www.github.com




kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
